"""Increase extra field length

Revision ID: 1f5d82f8730d
Revises: 4ad43ba63a11
Create Date: 2025-06-28 10:51:14.985318

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1f5d82f8730d"
down_revision = "4ad43ba63a11"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
