"""Increase size of extra field in InboundConfig

Revision ID: 4ad43ba63a11
Revises: 8d06d308ae47
Create Date: 2025-06-28 10:42:41.365052

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4ad43ba63a11"
down_revision = "8d06d308ae47"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
