"""Revert column lengths and ensure extra field length is correct

Revision ID: 57b0e3b6f599
Revises: a3da56ab4a2e
Create Date: 2025-06-28 11:04:11.228884

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "57b0e3b6f599"
down_revision = "a3da56ab4a2e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
