"""Add mode and extra fields to InboundConfig

Revision ID: 8d06d308ae47
Revises: b89acf39a86a
Create Date: 2025-06-27 18:04:46.494484

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8d06d308ae47"
down_revision = "b89acf39a86a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inbound_config",
        sa.Column("mode", sa.String(length=128), nullable=False, server_default="auto"),
    )
    op.add_column(
        "inbound_config", sa.Column("extra", sa.String(length=2048), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inbound_config", "extra")
    op.drop_column("inbound_config", "mode")
    # ### end Alembic commands ###
