"""Increase extra field length in InboundConfig model

Revision ID: a3da56ab4a2e
Revises: 1f5d82f8730d
Create Date: 2025-06-28 10:57:49.167384

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a3da56ab4a2e"
down_revision = "1f5d82f8730d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
